apiVersion: apps/v1
kind: Deployment
metadata:
  name: iq-user-profile-ds
  labels:
    app: iq-user-profile-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iq-user-profile-ds
  template:
    metadata:
      labels:
        app: iq-user-profile-ds
    spec:
      containers:
      - name: iq-user-profile-ds
        image: 319472806911.dkr.ecr.us-east-2.amazonaws.com/iq-user-profile-ds:${BUILD_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 21032
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 512Mi
            cpu: 240m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livelinessProbe:
            httpGet:
              path: /api/iq/ds/userprofile/v1/lives
              port: 21032
              initialDelaySeconds: 30
              periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/iq/ds/userprofile/v1/ready
              port: 21032
              initialDelaySeconds: 30
              periodSeconds: 10
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
        envFrom:
          - configMapRef:
              name: environment
          - secretRef:
              name: prometheus-credentials
          - secretRef:
              name: {{ secretNameDs }}
          - secretRef:
              name: {{ commonSecretMod }}

---
kind: Service
apiVersion: v1
metadata:
  name: iq-user-profile-ds
  labels:
    app: iq-user-profile-ds
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 21032
      protocol: TCP 
      targetPort: 21032
    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: iq-user-profile-ds

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata: 
  name: iq-user-profile-ds
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: {{ secretNameDs }}
  rules:
  - host: {{ internalHostNameDs }}
    http:
      paths:
      - backend:
          service:
            name: iq-user-profile-ds
            port:
              number: 21032
        path: /api/iq/ds/userprofile
        pathType: ImplementationSpecific

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iq-user-profile-ds
  namespace: iqm-micro
spec:
  endpoints:
    - basicAuth:
        password:
          name: prometheus-credentials
          key: MONITORING_PROMETHEUS_PASSWORD
        username:
          name: prometheus-credentials
          key: MONITORING_PROMETHEUS_USERNAME
      path: /actuator/prometheus
      port: metrics
  selector:
    matchLabels:
      app: iq-user-profile-ds
